version: "3.9"
services:
  workflow:
    build: .
    container_name: workflow_data
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - mysql
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql #Run init.sql debug connect mysql wrong port
      - ./data/mysql:/var/lib/mysql 
volumes:
  mongodb_data:
  mysql_data:
